SELECT

CAST(TO_TIMESTAMP(RECORDDATE2, 'YYYY/MM/DD HH24:MI')AS DATE) AS WATCH_DATE,
CAST(TO_TIMESTAMP(RECORDDATE2, 'YYYY/MM/DD HH24:MI')AS TIME) AS WATCH_TIME,
DAYOFMONTH(WATCH_DATE) AS DAY_OF_MONTH,
TO_CHAR(WATCH_DATE,'YYYYMM') AS MONTH_ID,
MONTHNAME(WATCH_DATE)AS MONTH_NAME,

 CASE
WHEN WATCH_TIME BETWEEN '06:00:00' AND '11:59:59' THEN 'MORNING'
WHEN WATCH_TIME BETWEEN '12:00:00' AND '16:59:59' THEN 'AFTERNOON'
WHEN WATCH_TIME BETWEEN '17:00:00' AND '20:59:59' THEN 'EVENING'
ELSE 'NIGHT'
END AS TIME_BUCKETS,

CASE 
WHEN age between 0 AND 29 THEN 'YOUNG'
WHEN age between 30 AND 59 THEN 'ADULT'
WHEN age BETWEEN 60 AND 89 THEN 'ELDER'
ELSE 'SENIOR'
END AS TIME_BUCKET,

--COUNT HOW MANY PEOPLE ARE SIGNED UP
COUNT (DISTINCT EMAIL) AS NUMBER_OF_USERS,

*FROM "BRIGHTTV"."PUBLIC"."VIEWSHIP" AS VIEWSHIP
inner JOIN  "BRIGHTTV"."PUBLIC"."USERPROFILE" AS USER
ON VIEWSHIP.userid=user.userid
GROUP BY ALL
;
